version: '3'
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app 
    working_dir: /app
    command: npm run start:dev 
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
